list(APPEND FFMPEG_AVCODEC_HEADERS
    a64colors.h
    a64tables.h
    aac.h
    aac_ac3_parser.h
    aac_defines.h
    aaccoder_trellis.h
    aaccoder_twoloop.h
    aacenc.h
    aacenc_is.h
    aacenc_ltp.h
    aacenc_pred.h
    aacenc_quantization.h
    aacenc_quantization_misc.h
    aacenc_tns.h
    aacenc_utils.h
    aacencdsp.h
    aacenctab.h
    aacps.h
    aacps_fixed_tablegen.h
    aacps_tablegen.h
    aacpsdsp.h
    aacsbr.h
    aacsbrdata.h
    aactab.h
    aandcttab.h
    ac3.h
    ac3_channel_layout_tab.h
    ac3_parser.h
    ac3_parser_internal.h
    ac3dec.h
    ac3dec_data.h
    ac3defs.h
    ac3dsp.h
    ac3enc.h
    ac3tab.h
    acelp_filters.h
    acelp_pitch_delay.h
    acelp_vectors.h
    adpcm.h
    adpcm_data.h
    adts_header.h
    adts_parser.h
    adx.h
    alac_data.h
    alacdsp.h
    amfenc.h
    amr.h
    amrnbdata.h
    amrwbdata.h
    aom_film_grain.h
    apng.h
    aptx.h
    ass.h
    ass_split.h
    asv.h
    atrac.h
    atrac1data.h
    atrac3data.h
    atrac3plus.h
    atrac3plus_data.h
    atrac9tab.h
    atsc_a53.h
    audio_frame_queue.h
    audiodsp.h
    av1.h
    av1_levels.h
    av1_parse.h
    av1dec.h
    avcodec.h
    avcodec_internal.h
    avdct.h
    avfft.h
    avs2.h
    avs3.h
    bethsoftvideo.h
    bgmc.h
    binkdata.h
    binkdsp.h
    bintext.h
    bitstream.h
    bitstream_template.h
    blockdsp.h
    bmp.h
    bsf.h
    bsf_internal.h
    bswapdsp.h
    bytestream.h
    cabac.h
    cabac_functions.h
    canopus.h
    cavs.h
    cavsdsp.h
    cbrt_data.h
    cbrt_tablegen.h
    cbs.h
    cbs_av1.h
    cbs_bsf.h
    cbs_h264.h
    cbs_h2645.h
    cbs_h265.h
    cbs_h266.h
    cbs_internal.h
    cbs_jpeg.h
    cbs_mpeg2.h
    cbs_sei.h
    cbs_vp8.h
    cbs_vp9.h
    celp_filters.h
    celp_math.h
    cfhd.h
    cfhddsp.h
    cfhdencdsp.h
    cga_data.h
    clearvideodata.h
    codec.h
    codec2utils.h
    codec_desc.h
    codec_id.h
    codec_internal.h
    codec_par.h
    cookdata.h
    copy_block.h
    d3d11va.h
    d3d12va_decode.h
    dca.h
    dca_core.h
    dca_exss.h
    dca_lbr.h
    dca_sample_rate_tab.h
    dca_syncwords.h
    dca_xll.h
    dcaadpcm.h
    dcadata.h
    dcadct.h
    dcadec.h
    dcadsp.h
    dcaenc.h
    dcahuff.h
    dcamath.h
    dct.h
    dct32.h
    dctref.h
    decode.h
    defs.h
    dirac.h
    dirac_arith.h
    dirac_dwt.h
    dirac_vlc.h
    diracdsp.h
    diractab.h
    dnxhddata.h
    dnxhdenc.h
    dolby_e.h
    dovi_rpu.h
    dsd.h
    dv.h
    dv_internal.h
    dv_profile.h
    dv_profile_internal.h
    dv_tablegen.h
    dvaudio.h
    dvbtxt.h
    dvdata.h
    dvdsub.h
    dxv.h
    dxva2.h
    dxva2_internal.h
    dynamic_hdr_vivid.h
    eac3_data.h
    eac3enc.h
    eaidct.h
    elbg.h
    elsdec.h
    encode.h
    error_resilience.h
    evc.h
    evc_parse.h
    evc_ps.h
    evrcdata.h
    exif.h
    exrdsp.h
    faandct.h
    faanidct.h
    faxcompr.h
    fdctdsp.h
    ffjni.h
    fflcms2.h
    ffv1.h
    fits.h
    flac.h
    flac_parse.h
    flacdata.h
    flacdsp.h
    flacencdsp.h
    flvdec.h
    flvenc.h
    fmtconvert.h
    frame_thread_encoder.h
    g722.h
    g722dsp.h
    g723_1.h
    g729.h
    g729data.h
    g729postfilter.h
    get_bits.h
    gif.h
    golomb.h
    gsm.h
    gsmdec_data.h
    h261.h
    h261enc.h
    h263.h
    h263data.h
    h263dec.h
    h263dsp.h
    h263enc.h
    h264.h
    h2645_parse.h
    h2645_sei.h
    h2645_vui.h
    h2645data.h
    h264_levels.h
    h264_mvpred.h
    h264_parse.h
    h264_ps.h
    h264_sei.h
    h264chroma.h
    h264data.h
    h264dec.h
    h264dsp.h
    h264idct.h
    h264pred.h
    h264qpel.h
    h265_profile_level.h
    h274.h
    hap.h
    hca_data.h
    hpeldsp.h
    hq_hqadata.h
    hq_hqadsp.h
    hqx.h
    hqxdsp.h
    htmlsubtitles.h
    huffman.h
    huffyuv.h
    huffyuvdsp.h
    huffyuvencdsp.h
    hwaccel_internal.h
    hwaccels.h
    hwconfig.h
    idctdsp.h
    iirfilter.h
    ilbcdata.h
    imcdata.h
    indeo2data.h
    indeo3data.h
    indeo4data.h
    indeo5data.h
    internal.h
    intrax8.h
    intrax8dsp.h
    intrax8huf.h
    itut35.h
    ivi.h
    ivi_dsp.h
    jacosub.h
    jni.h
    jpeg2000.h
    jpeg2000dec.h
    jpeg2000dsp.h
    jpeg2000dwt.h
    jpeg2000htdec.h
    jpegls.h
    jpeglsdec.h
    jpegquanttables.h
    jpegtables.h
    jpegtabs.h
    jpegxl.h
    jpegxl_parse.h
    kbdwin.h
    lagarithrac.h
    lcl.h
    leaddata.h
    leb.h
    libaom.h
    libjxl.h
    libopenh264.h
    libopus.h
    libvpx.h
    libwebpenc_common.h
    lossless_audiodsp.h
    lossless_videodsp.h
    lossless_videoencdsp.h
    lpc.h
    lpc_functions.h
    lsp.h
    lzf.h
    lzw.h
    mathops.h
    me_cmp.h
    mediacodec.h
    mediacodec_surface.h
    mediacodec_sw_buffer.h
    mediacodec_wrapper.h
    mediacodecdec_common.h
    metasound_data.h
    metasound_twinvq_data.h
    mf_utils.h
    mjpeg.h
    mjpegdec.h
    mjpegenc.h
    mjpegenc_common.h
    mjpegenc_huffman.h
    mlp.h
    mlp_parse.h
    mlpdsp.h
    mlz.h
    motion_est.h
    motionpixels_tablegen.h
    mpc.h
    mpc7data.h
    mpc8data.h
    mpc8huff.h
    mpcdata.h
    mpeg12.h
    mpeg12codecs.h
    mpeg12data.h
    mpeg12dec.h
    mpeg12enc.h
    mpeg12vlc.h
    mpeg4audio.h
    mpeg4audio_copy_pce.h
    mpeg4audio_sample_rates.h
    mpeg4data.h
    mpeg4video.h
    mpeg4videodata.h
    mpeg4videodec.h
    mpeg4videodefs.h
    mpeg4videodsp.h
    mpeg4videoenc.h
    mpeg_er.h
    mpegaudio.h
    mpegaudio_tablegen.h
    mpegaudiodata.h
    mpegaudiodec_common_tablegen.h
    mpegaudiodecheader.h
    mpegaudiodsp.h
    mpegaudiotab.h
    mpegaudiotabs.h
    mpegpicture.h
    mpegutils.h
    mpegvideo.h
    mpegvideodata.h
    mpegvideodec.h
    mpegvideoenc.h
    mpegvideoencdsp.h
    mqc.h
    msgsmdec.h
    msmpeg4.h
    msmpeg4_vc1_data.h
    msmpeg4data.h
    msmpeg4dec.h
    msmpeg4enc.h
    msrledec.h
    mss12.h
    mss2dsp.h
    mss34dsp.h
    nellymoser.h
    nvdec.h
    nvenc.h
    on2avcdata.h
    options_table.h
    opus.h
    opus_celt.h
    opus_parse.h
    opus_pvq.h
    opus_rc.h
    opus_silk.h
    opusdsp.h
    opusenc.h
    opusenc_psy.h
    opusenc_utils.h
    opustab.h
    packet.h
    packet_internal.h
    paf.h
    parser.h
    pcm_tablegen.h
    pixblockdsp.h
    pixels.h
    png.h
    pngdsp.h
    pnm.h
    profiles.h
    progressframe.h
    proresdata.h
    proresdec.h
    proresdsp.h
    psymodel.h
    pthread_internal.h
    put_bits.h
    put_golomb.h
    qcelpdata.h
    qdm2_tablegen.h
    qdm2data.h
    qoi.h
    qpeldsp.h
    qsv.h
    qsv_internal.h
    qsvenc.h
    ra144.h
    ra288.h
    ralfdata.h
    rangecoder.h
    ratecontrol.h
    raw.h
    rectangle.h
    refstruct.h
    rl.h
    rle.h
    rnd_avg.h
    roqvideo.h
    rtjpeg.h
    rv10dec.h
    rv10enc.h
    rv30data.h
    rv34.h
    rv34data.h
    rv34dsp.h
    rv34vlc.h
    rv40data.h
    rv40vlc2.h
    sbc.h
    sbcdec_data.h
    sbcdsp.h
    sbcdsp_data.h
    sbr.h
    sbrdsp.h
    scpr.h
    scpr3.h
    sei.h
    sgi.h
    sheervideodata.h
    simple_idct.h
    sinewin.h
    sinewin_fixed_tablegen.h
    sinewin_tablegen.h
    sipr.h
    sipr16kdata.h
    siprdata.h
    snappy.h
    snow.h
    snow_dwt.h
    snowdata.h
    sp5x.h
    speedhq.h
    speedhqenc.h
    speexdata.h
    startcode.h
    sunrast.h
    svq1.h
    svq1_cb.h
    svq1_vlc.h
    svq1enc_cb.h
    svq1encdsp.h
    synth_filter.h
    tableprint.h
    tableprint_vlc.h
    tak.h
    takdsp.h
    targa.h
    texturedsp.h
    thread.h
    threadframe.h
    threadprogress.h
    tiff.h
    tiff_common.h
    tiff_data.h
    to_upper4.h
    tpeldsp.h
    truemotion1data.h
    truespeech_data.h
    tscc2data.h
    ttadata.h
    ttadsp.h
    ttaencdsp.h
    ttmlenc.h
    twinvq.h
    twinvq_data.h
    ulti_cb.h
    unary.h
    utvideo.h
    utvideodsp.h
    v210dec.h
    v210dec_init.h
    v210enc.h
    v210enc_init.h
    v4l2_buffers.h
    v4l2_context.h
    v4l2_fmt.h
    v4l2_m2m.h
    vaapi_decode.h
    vaapi_encode.h
    vaapi_hevc.h
    vbn.h
    vc1.h
    vc1_common.h
    vc1_pred.h
    vc1_vlc_data.h
    vc1acdata.h
    vc1data.h
    vc1dsp.h
    vc2enc_dwt.h
    vdpau.h
    vdpau_internal.h
    version.h
    version_major.h
    videodsp.h
    videotoolbox.h
    vlc.h
    vorbis.h
    vorbis_data.h
    vorbis_enc_data.h
    vorbis_parser.h
    vorbis_parser_internal.h
    vorbisdsp.h
    vp3data.h
    vp3dsp.h
    vp4data.h
    vp56.h
    vp56data.h
    vp56dsp.h
    vp5data.h
    vp6data.h
    vp8.h
    vp89_rac.h
    vp8data.h
    vp8dsp.h
    vp9.h
    vp9data.h
    vp9dec.h
    vp9dsp.h
    vp9shared.h
    vpx_rac.h
    vt_internal.h
    vulkan.h
    vulkan_decode.h
    vulkan_video.h
    vvc.h
    wavpack.h
    wavpackenc.h
    wma.h
    wma_common.h
    wma_freqs.h
    wmadata.h
    wmaprodata.h
    wmavoice_data.h
    wmv2.h
    wmv2data.h
    wmv2dec.h
    wmv2dsp.h
    wmv2enc.h
    xface.h
    xiph.h
    xvididct.h
    xwd.h
    zlib_wrapper.h
)
