#list(APPEND FFMPEG_AVFORMAT_CORE_SOURCES h264dec.c)
list(APPEND FFMPEG_AVFORMAT_CORE_SOURCES_PREPENDED
    h264dec.c "#include \"libavutil/internal.h\""
)

list(APPEND FFMPEG_AVFORMAT_DEMUXERS "ff_h264_demuxer")
