list(APPEND ffmpeg.avfilter.header_names
    af_afirdsp.h
    af_anlmdndsp.h
    af_volume.h
    atadenoise.h
    audio.h
    avf_showcqt.h
    avfilter.h
    avfilter_internal.h
    bbox.h
    blend.h
    boxblur.h
    bufferqueue.h
    buffersink.h
    buffersrc.h
    bwdifdsp.h
    ccfifo.h
    colorspace.h
    colorspacedsp.h
    convolution.h
    dnn_filter_common.h
    dnn_interface.h
    drawutils.h
    ebur128.h
    edge_common.h
    fflcms2.h
    filters.h
    formats.h
    framepool.h
    framequeue.h
    framerate.h
    framesync.h
    gblur.h
    generate_wave_table.h
    gradfun.h
    hermite.h
    hflip.h
    internal.h
    lavfutils.h
    limiter.h
    lswsutils.h
    lut3d.h
    maskedclamp.h
    maskedmerge.h
    median.h
    motion_estimation.h
    opencl.h
    opencl_source.h
    palette.h
    preserve_color.h
    psnr.h
    qp_table.h
    qsvvpp.h
    removegrain.h
    scale_eval.h
    scene_sad.h
    signature.h
    ssim.h
    stack_internal.h
    stereo3d.h
    textutils.h
    threshold.h
    tinterlace.h
    transform.h
    transpose.h
    unsharp.h
    v360.h
    vaapi_vpp.h
    version.h
    version_major.h
    vf_blend_init.h
    vf_eq.h
    vf_fspp.h
    vf_gblur_init.h
    vf_hflip_init.h
    vf_hqdn3d.h
    vf_idet.h
    vf_nlmeans.h
    vf_nlmeans_init.h
    vf_noise.h
    vf_overlay.h
    vf_pp7.h
    vf_pullup.h
    vf_scale_cuda.h
    vf_spp.h
    vf_threshold_init.h
    video.h
    vidstabutils.h
    vmaf_motion.h
    vsrc_ddagrab_shaders.h
    vulkan.h
    vulkan_filter.h
    vulkan_spirv.h
    w3fdif.h
    window_func.h
    yadif.h
)
